name: Icon update
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone media repository
        run: |
            git clone https://github.com/buckaroo-it/Media
            ls -lah
      - name: Rename all files to lowercase
        run: |
            cd Media
            cp ${{ github.workspace }}/.github/workflows/rename-icons.php ${{ github.workspace }}/Media/rename-icons.php
            php  ./rename-icons.php
      - name: Copy payment method icons
        run: |
            cd Media
            cp -R "Payment methods/SVG/." ${{ github.workspace }}/Views/frontend/_resources/images/payments/
            cd ${{ github.workspace }}/Views/frontend/_resources/images/payments/
            rm -f ideal-qr.svg knaken.svg paylink.svg paybybank.svg pos.svg alipay.svg buckaroovoucher.svg creditclick.svg tinka.svg vouchers.svg wechatpay.svg payperemail.svg belfius.svg in3.svg trustly.svg mbway.svg multibanco.svg pos-nfc.svg riverty.svg
      - name: Copy creditcards icons
        run: |
            cd Media
            cp -R "Creditcard issuers/SVG/." ${{ github.workspace }}/Views/frontend/_resources/images/creditcards/
      - name: Cleanup
        run: |
            rm -rd Media
      - name: Create commit if we have changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply logo changes from media repository